//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.20 at 10:28:24 AM WEST 
//


package ma.supmti.forum.data.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}fateliers"/>
 *         &lt;element ref="{}inscrits"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fateliers",
    "inscrits"
})
@XmlRootElement(name = "forum")
public class Forum {

    @XmlElement(required = true)
    protected Fateliers fateliers;
    @XmlElement(required = true)
    protected Inscrits inscrits;

    /**
     * Gets the value of the fateliers property.
     * 
     * @return
     *     possible object is
     *     {@link Fateliers }
     *     
     */
    public Fateliers getFateliers() {
        return fateliers;
    }

    /**
     * Sets the value of the fateliers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fateliers }
     *     
     */
    public void setFateliers(Fateliers value) {
        this.fateliers = value;
    }

    /**
     * Gets the value of the inscrits property.
     * 
     * @return
     *     possible object is
     *     {@link Inscrits }
     *     
     */
    public Inscrits getInscrits() {
        return inscrits;
    }

    /**
     * Sets the value of the inscrits property.
     * 
     * @param value
     *     allowed object is
     *     {@link Inscrits }
     *     
     */
    public void setInscrits(Inscrits value) {
        this.inscrits = value;
    }

}
