//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.20 at 10:28:24 AM WEST 
//


package ma.supmti.forum.data.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ma.supmti.forum.data.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Prenom_QNAME = new QName("", "prenom");
    private final static QName _Email_QNAME = new QName("", "email");
    private final static QName _Telephone_QNAME = new QName("", "telephone");
    private final static QName _Nom_QNAME = new QName("", "nom");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ma.supmti.forum.data.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Forum }
     * 
     */
    public Forum createForum() {
        return new Forum();
    }

    /**
     * Create an instance of {@link Fateliers }
     * 
     */
    public Fateliers createFateliers() {
        return new Fateliers();
    }

    /**
     * Create an instance of {@link Fatelier }
     * 
     */
    public Fatelier createFatelier() {
        return new Fatelier();
    }

    /**
     * Create an instance of {@link Inscrits }
     * 
     */
    public Inscrits createInscrits() {
        return new Inscrits();
    }

    /**
     * Create an instance of {@link Inscrit }
     * 
     */
    public Inscrit createInscrit() {
        return new Inscrit();
    }

    /**
     * Create an instance of {@link Ateliers }
     * 
     */
    public Ateliers createAteliers() {
        return new Ateliers();
    }

    /**
     * Create an instance of {@link Atelier }
     * 
     */
    public Atelier createAtelier() {
        return new Atelier();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "prenom")
    public JAXBElement<String> createPrenom(String value) {
        return new JAXBElement<String>(_Prenom_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "email")
    public JAXBElement<String> createEmail(String value) {
        return new JAXBElement<String>(_Email_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "telephone")
    public JAXBElement<String> createTelephone(String value) {
        return new JAXBElement<String>(_Telephone_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nom")
    public JAXBElement<String> createNom(String value) {
        return new JAXBElement<String>(_Nom_QNAME, String.class, null, value);
    }

}
